// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Message struct {
	ID       string
	Created  time.Time
	Username string
	Channel  string
	Text     string
}

type Migration struct {
	ID      string
	Applied time.Time
}
