// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	//CountMessages
	//
	//  SELECT COUNT(*) from messages
	CountMessages(ctx context.Context) (int64, error)
	//CreateMessage
	//
	//  INSERT INTO messages (id, created, channel, username, text)
	//  VALUES ($1, $2, $3, $4, $5)
	CreateMessage(ctx context.Context, arg CreateMessageParams) error
	//CreateMigration
	//
	//  INSERT INTO migration (id, applied)
	//  VALUES ($1, $2) RETURNING id
	CreateMigration(ctx context.Context, arg CreateMigrationParams) (string, error)
	//GetMigrations
	//
	//  SELECT id, applied
	//  FROM migration
	//  ORDER BY id
	GetMigrations(ctx context.Context) ([]Migration, error)
}

var _ Querier = (*Queries)(nil)
