// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/store.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/store.go -destination internal/repository/mocks/store_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/rofleksey/dredge/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ActiveStreamIDForChannel mocks base method.
func (m *MockStore) ActiveStreamIDForChannel(ctx context.Context, channelTwitchUserID int64) (*int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveStreamIDForChannel", ctx, channelTwitchUserID)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveStreamIDForChannel indicates an expected call of ActiveStreamIDForChannel.
func (mr *MockStoreMockRecorder) ActiveStreamIDForChannel(ctx, channelTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveStreamIDForChannel", reflect.TypeOf((*MockStore)(nil).ActiveStreamIDForChannel), ctx, channelTwitchUserID)
}

// AddChannelBlacklist mocks base method.
func (m *MockStore) AddChannelBlacklist(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChannelBlacklist", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChannelBlacklist indicates an expected call of AddChannelBlacklist.
func (mr *MockStoreMockRecorder) AddChannelBlacklist(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChannelBlacklist", reflect.TypeOf((*MockStore)(nil).AddChannelBlacklist), ctx, login)
}

// CloseOpenStreamsForChannel mocks base method.
func (m *MockStore) CloseOpenStreamsForChannel(ctx context.Context, channelTwitchUserID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseOpenStreamsForChannel", ctx, channelTwitchUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseOpenStreamsForChannel indicates an expected call of CloseOpenStreamsForChannel.
func (mr *MockStoreMockRecorder) CloseOpenStreamsForChannel(ctx, channelTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseOpenStreamsForChannel", reflect.TypeOf((*MockStore)(nil).CloseOpenStreamsForChannel), ctx, channelTwitchUserID)
}

// CountChannelChatters mocks base method.
func (m *MockStore) CountChannelChatters(ctx context.Context, channelTwitchUserID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChannelChatters", ctx, channelTwitchUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChannelChatters indicates an expected call of CountChannelChatters.
func (mr *MockStoreMockRecorder) CountChannelChatters(ctx, channelTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChannelChatters", reflect.TypeOf((*MockStore)(nil).CountChannelChatters), ctx, channelTwitchUserID)
}

// CountChatMessages mocks base method.
func (m *MockStore) CountChatMessages(ctx context.Context, f entity.ChatMessageListFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChatMessages", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChatMessages indicates an expected call of CountChatMessages.
func (mr *MockStoreMockRecorder) CountChatMessages(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChatMessages", reflect.TypeOf((*MockStore)(nil).CountChatMessages), ctx, f)
}

// CountChatMessagesByChatter mocks base method.
func (m *MockStore) CountChatMessagesByChatter(ctx context.Context, chatterID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChatMessagesByChatter", ctx, chatterID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChatMessagesByChatter indicates an expected call of CountChatMessagesByChatter.
func (mr *MockStoreMockRecorder) CountChatMessagesByChatter(ctx, chatterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChatMessagesByChatter", reflect.TypeOf((*MockStore)(nil).CountChatMessagesByChatter), ctx, chatterID)
}

// CountChatMessagesPerChatterForChannelSince mocks base method.
func (m *MockStore) CountChatMessagesPerChatterForChannelSince(ctx context.Context, channelTwitchUserID int64, since time.Time) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChatMessagesPerChatterForChannelSince", ctx, channelTwitchUserID, since)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChatMessagesPerChatterForChannelSince indicates an expected call of CountChatMessagesPerChatterForChannelSince.
func (mr *MockStoreMockRecorder) CountChatMessagesPerChatterForChannelSince(ctx, channelTwitchUserID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChatMessagesPerChatterForChannelSince", reflect.TypeOf((*MockStore)(nil).CountChatMessagesPerChatterForChannelSince), ctx, channelTwitchUserID, since)
}

// CountChatMessagesPerChatterForStream mocks base method.
func (m *MockStore) CountChatMessagesPerChatterForStream(ctx context.Context, streamID int64) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountChatMessagesPerChatterForStream", ctx, streamID)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountChatMessagesPerChatterForStream indicates an expected call of CountChatMessagesPerChatterForStream.
func (mr *MockStoreMockRecorder) CountChatMessagesPerChatterForStream(ctx, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountChatMessagesPerChatterForStream", reflect.TypeOf((*MockStore)(nil).CountChatMessagesPerChatterForStream), ctx, streamID)
}

// CountRules mocks base method.
func (m *MockStore) CountRules(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRules", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRules indicates an expected call of CountRules.
func (mr *MockStoreMockRecorder) CountRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRules", reflect.TypeOf((*MockStore)(nil).CountRules), ctx)
}

// CountTwitchAccounts mocks base method.
func (m *MockStore) CountTwitchAccounts(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTwitchAccounts", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTwitchAccounts indicates an expected call of CountTwitchAccounts.
func (mr *MockStoreMockRecorder) CountTwitchAccounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTwitchAccounts", reflect.TypeOf((*MockStore)(nil).CountTwitchAccounts), ctx)
}

// CountTwitchUsersBrowse mocks base method.
func (m *MockStore) CountTwitchUsersBrowse(ctx context.Context, f entity.TwitchUserBrowseFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTwitchUsersBrowse", ctx, f)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTwitchUsersBrowse indicates an expected call of CountTwitchUsersBrowse.
func (mr *MockStoreMockRecorder) CountTwitchUsersBrowse(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTwitchUsersBrowse", reflect.TypeOf((*MockStore)(nil).CountTwitchUsersBrowse), ctx, f)
}

// CreateNotificationEntry mocks base method.
func (m *MockStore) CreateNotificationEntry(ctx context.Context, provider string, settings map[string]any, enabled bool) (entity.NotificationEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationEntry", ctx, provider, settings, enabled)
	ret0, _ := ret[0].(entity.NotificationEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotificationEntry indicates an expected call of CreateNotificationEntry.
func (mr *MockStoreMockRecorder) CreateNotificationEntry(ctx, provider, settings, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationEntry", reflect.TypeOf((*MockStore)(nil).CreateNotificationEntry), ctx, provider, settings, enabled)
}

// CreateRule mocks base method.
func (m *MockStore) CreateRule(ctx context.Context, r entity.Rule) (entity.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, r)
	ret0, _ := ret[0].(entity.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockStoreMockRecorder) CreateRule(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockStore)(nil).CreateRule), ctx, r)
}

// CreateTwitchAccount mocks base method.
func (m *MockStore) CreateTwitchAccount(ctx context.Context, id int64, username, refreshToken, accountType string) (entity.TwitchAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTwitchAccount", ctx, id, username, refreshToken, accountType)
	ret0, _ := ret[0].(entity.TwitchAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTwitchAccount indicates an expected call of CreateTwitchAccount.
func (mr *MockStoreMockRecorder) CreateTwitchAccount(ctx, id, username, refreshToken, accountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTwitchAccount", reflect.TypeOf((*MockStore)(nil).CreateTwitchAccount), ctx, id, username, refreshToken, accountType)
}

// CreateTwitchUser mocks base method.
func (m *MockStore) CreateTwitchUser(ctx context.Context, id int64, username string) (entity.TwitchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTwitchUser", ctx, id, username)
	ret0, _ := ret[0].(entity.TwitchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTwitchUser indicates an expected call of CreateTwitchUser.
func (mr *MockStoreMockRecorder) CreateTwitchUser(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTwitchUser", reflect.TypeOf((*MockStore)(nil).CreateTwitchUser), ctx, id, username)
}

// DeleteChannelChatterPresence mocks base method.
func (m *MockStore) DeleteChannelChatterPresence(ctx context.Context, channelTwitchUserID, chatterTwitchUserID int64) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannelChatterPresence", ctx, channelTwitchUserID, chatterTwitchUserID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteChannelChatterPresence indicates an expected call of DeleteChannelChatterPresence.
func (mr *MockStoreMockRecorder) DeleteChannelChatterPresence(ctx, channelTwitchUserID, chatterTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannelChatterPresence", reflect.TypeOf((*MockStore)(nil).DeleteChannelChatterPresence), ctx, channelTwitchUserID, chatterTwitchUserID)
}

// DeleteNotificationEntry mocks base method.
func (m *MockStore) DeleteNotificationEntry(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotificationEntry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotificationEntry indicates an expected call of DeleteNotificationEntry.
func (mr *MockStoreMockRecorder) DeleteNotificationEntry(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotificationEntry", reflect.TypeOf((*MockStore)(nil).DeleteNotificationEntry), ctx, id)
}

// DeleteRule mocks base method.
func (m *MockStore) DeleteRule(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockStoreMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockStore)(nil).DeleteRule), ctx, id)
}

// DeleteTwitchAccount mocks base method.
func (m *MockStore) DeleteTwitchAccount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTwitchAccount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTwitchAccount indicates an expected call of DeleteTwitchAccount.
func (mr *MockStoreMockRecorder) DeleteTwitchAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTwitchAccount", reflect.TypeOf((*MockStore)(nil).DeleteTwitchAccount), ctx, id)
}

// GetHelixMeta mocks base method.
func (m *MockStore) GetHelixMeta(ctx context.Context, twitchUserID int64) (*time.Time, *time.Time, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHelixMeta", ctx, twitchUserID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(*string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetHelixMeta indicates an expected call of GetHelixMeta.
func (mr *MockStoreMockRecorder) GetHelixMeta(ctx, twitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHelixMeta", reflect.TypeOf((*MockStore)(nil).GetHelixMeta), ctx, twitchUserID)
}

// GetIrcMonitorSettings mocks base method.
func (m *MockStore) GetIrcMonitorSettings(ctx context.Context) (entity.IrcMonitorSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIrcMonitorSettings", ctx)
	ret0, _ := ret[0].(entity.IrcMonitorSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIrcMonitorSettings indicates an expected call of GetIrcMonitorSettings.
func (mr *MockStoreMockRecorder) GetIrcMonitorSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIrcMonitorSettings", reflect.TypeOf((*MockStore)(nil).GetIrcMonitorSettings), ctx)
}

// GetMonitoredStreamByID mocks base method.
func (m *MockStore) GetMonitoredStreamByID(ctx context.Context, id int64) (entity.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitoredStreamByID", ctx, id)
	ret0, _ := ret[0].(entity.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitoredStreamByID indicates an expected call of GetMonitoredStreamByID.
func (mr *MockStoreMockRecorder) GetMonitoredStreamByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitoredStreamByID", reflect.TypeOf((*MockStore)(nil).GetMonitoredStreamByID), ctx, id)
}

// GetStreamByID mocks base method.
func (m *MockStore) GetStreamByID(ctx context.Context, id int64) (entity.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamByID", ctx, id)
	ret0, _ := ret[0].(entity.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamByID indicates an expected call of GetStreamByID.
func (mr *MockStoreMockRecorder) GetStreamByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamByID", reflect.TypeOf((*MockStore)(nil).GetStreamByID), ctx, id)
}

// GetSuspicionSettings mocks base method.
func (m *MockStore) GetSuspicionSettings(ctx context.Context) (entity.SuspicionSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuspicionSettings", ctx)
	ret0, _ := ret[0].(entity.SuspicionSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuspicionSettings indicates an expected call of GetSuspicionSettings.
func (mr *MockStoreMockRecorder) GetSuspicionSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuspicionSettings", reflect.TypeOf((*MockStore)(nil).GetSuspicionSettings), ctx)
}

// GetTwitchAccountByID mocks base method.
func (m *MockStore) GetTwitchAccountByID(ctx context.Context, id int64) (entity.TwitchAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTwitchAccountByID", ctx, id)
	ret0, _ := ret[0].(entity.TwitchAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwitchAccountByID indicates an expected call of GetTwitchAccountByID.
func (mr *MockStoreMockRecorder) GetTwitchAccountByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwitchAccountByID", reflect.TypeOf((*MockStore)(nil).GetTwitchAccountByID), ctx, id)
}

// GetTwitchAccountByTwitchUserID mocks base method.
func (m *MockStore) GetTwitchAccountByTwitchUserID(ctx context.Context, twitchUserID int64) (entity.TwitchAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTwitchAccountByTwitchUserID", ctx, twitchUserID)
	ret0, _ := ret[0].(entity.TwitchAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwitchAccountByTwitchUserID indicates an expected call of GetTwitchAccountByTwitchUserID.
func (mr *MockStoreMockRecorder) GetTwitchAccountByTwitchUserID(ctx, twitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwitchAccountByTwitchUserID", reflect.TypeOf((*MockStore)(nil).GetTwitchAccountByTwitchUserID), ctx, twitchUserID)
}

// GetTwitchUserByID mocks base method.
func (m *MockStore) GetTwitchUserByID(ctx context.Context, id int64) (entity.TwitchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTwitchUserByID", ctx, id)
	ret0, _ := ret[0].(entity.TwitchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTwitchUserByID indicates an expected call of GetTwitchUserByID.
func (mr *MockStoreMockRecorder) GetTwitchUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTwitchUserByID", reflect.TypeOf((*MockStore)(nil).GetTwitchUserByID), ctx, id)
}

// InsertChatMessage mocks base method.
func (m *MockStore) InsertChatMessage(ctx context.Context, channelTwitchUserID int64, chatterTwitchUserID *int64, chatterUsername, body string, keywordMatch bool, msgType string, badgeTags []string, firstMessage bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertChatMessage", ctx, channelTwitchUserID, chatterTwitchUserID, chatterUsername, body, keywordMatch, msgType, badgeTags, firstMessage)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertChatMessage indicates an expected call of InsertChatMessage.
func (mr *MockStoreMockRecorder) InsertChatMessage(ctx, channelTwitchUserID, chatterTwitchUserID, chatterUsername, body, keywordMatch, msgType, badgeTags, firstMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertChatMessage", reflect.TypeOf((*MockStore)(nil).InsertChatMessage), ctx, channelTwitchUserID, chatterTwitchUserID, chatterUsername, body, keywordMatch, msgType, badgeTags, firstMessage)
}

// InsertChatMessageForChannelLogin mocks base method.
func (m *MockStore) InsertChatMessageForChannelLogin(ctx context.Context, channelLogin string, chatterTwitchUserID *int64, chatterUsername, body string, keywordMatch bool, msgType string, badgeTags []string, firstMessage bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertChatMessageForChannelLogin", ctx, channelLogin, chatterTwitchUserID, chatterUsername, body, keywordMatch, msgType, badgeTags, firstMessage)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertChatMessageForChannelLogin indicates an expected call of InsertChatMessageForChannelLogin.
func (mr *MockStoreMockRecorder) InsertChatMessageForChannelLogin(ctx, channelLogin, chatterTwitchUserID, chatterUsername, body, keywordMatch, msgType, badgeTags, firstMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertChatMessageForChannelLogin", reflect.TypeOf((*MockStore)(nil).InsertChatMessageForChannelLogin), ctx, channelLogin, chatterTwitchUserID, chatterUsername, body, keywordMatch, msgType, badgeTags, firstMessage)
}

// InsertUserActivityEvent mocks base method.
func (m *MockStore) InsertUserActivityEvent(ctx context.Context, chatterID int64, eventType string, channelTwitchUserID *int64, details map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUserActivityEvent", ctx, chatterID, eventType, channelTwitchUserID, details)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertUserActivityEvent indicates an expected call of InsertUserActivityEvent.
func (mr *MockStoreMockRecorder) InsertUserActivityEvent(ctx, chatterID, eventType, channelTwitchUserID, details any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUserActivityEvent", reflect.TypeOf((*MockStore)(nil).InsertUserActivityEvent), ctx, chatterID, eventType, channelTwitchUserID, details)
}

// IsMonitoredChannel mocks base method.
func (m *MockStore) IsMonitoredChannel(ctx context.Context, channel string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMonitoredChannel", ctx, channel)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMonitoredChannel indicates an expected call of IsMonitoredChannel.
func (mr *MockStoreMockRecorder) IsMonitoredChannel(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMonitoredChannel", reflect.TypeOf((*MockStore)(nil).IsMonitoredChannel), ctx, channel)
}

// IsTwitchUserMarked mocks base method.
func (m *MockStore) IsTwitchUserMarked(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTwitchUserMarked", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTwitchUserMarked indicates an expected call of IsTwitchUserMarked.
func (mr *MockStoreMockRecorder) IsTwitchUserMarked(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTwitchUserMarked", reflect.TypeOf((*MockStore)(nil).IsTwitchUserMarked), ctx, id)
}

// IsTwitchUserSuspicious mocks base method.
func (m *MockStore) IsTwitchUserSuspicious(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTwitchUserSuspicious", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTwitchUserSuspicious indicates an expected call of IsTwitchUserSuspicious.
func (mr *MockStoreMockRecorder) IsTwitchUserSuspicious(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTwitchUserSuspicious", reflect.TypeOf((*MockStore)(nil).IsTwitchUserSuspicious), ctx, id)
}

// ListChannelBlacklist mocks base method.
func (m *MockStore) ListChannelBlacklist(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannelBlacklist", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannelBlacklist indicates an expected call of ListChannelBlacklist.
func (mr *MockStoreMockRecorder) ListChannelBlacklist(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannelBlacklist", reflect.TypeOf((*MockStore)(nil).ListChannelBlacklist), ctx)
}

// ListChannelChatterEntries mocks base method.
func (m *MockStore) ListChannelChatterEntries(ctx context.Context, channelTwitchUserID int64) ([]entity.ChannelChatterEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannelChatterEntries", ctx, channelTwitchUserID)
	ret0, _ := ret[0].([]entity.ChannelChatterEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannelChatterEntries indicates an expected call of ListChannelChatterEntries.
func (mr *MockStoreMockRecorder) ListChannelChatterEntries(ctx, channelTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannelChatterEntries", reflect.TypeOf((*MockStore)(nil).ListChannelChatterEntries), ctx, channelTwitchUserID)
}

// ListChannelChatterIDs mocks base method.
func (m *MockStore) ListChannelChatterIDs(ctx context.Context, channelTwitchUserID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannelChatterIDs", ctx, channelTwitchUserID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannelChatterIDs indicates an expected call of ListChannelChatterIDs.
func (mr *MockStoreMockRecorder) ListChannelChatterIDs(ctx, channelTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannelChatterIDs", reflect.TypeOf((*MockStore)(nil).ListChannelChatterIDs), ctx, channelTwitchUserID)
}

// ListChatHistory mocks base method.
func (m *MockStore) ListChatHistory(ctx context.Context, channel string, limit int) ([]entity.ChatHistoryMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatHistory", ctx, channel, limit)
	ret0, _ := ret[0].([]entity.ChatHistoryMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatHistory indicates an expected call of ListChatHistory.
func (mr *MockStoreMockRecorder) ListChatHistory(ctx, channel, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatHistory", reflect.TypeOf((*MockStore)(nil).ListChatHistory), ctx, channel, limit)
}

// ListChatMessages mocks base method.
func (m *MockStore) ListChatMessages(ctx context.Context, f entity.ChatMessageListFilter) ([]entity.ChatHistoryMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatMessages", ctx, f)
	ret0, _ := ret[0].([]entity.ChatHistoryMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatMessages indicates an expected call of ListChatMessages.
func (mr *MockStoreMockRecorder) ListChatMessages(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatMessages", reflect.TypeOf((*MockStore)(nil).ListChatMessages), ctx, f)
}

// ListChatterChannelPairsForFollowEnrichment mocks base method.
func (m *MockStore) ListChatterChannelPairsForFollowEnrichment(ctx context.Context, limit int) ([]entity.ChatterChannelPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatterChannelPairsForFollowEnrichment", ctx, limit)
	ret0, _ := ret[0].([]entity.ChatterChannelPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatterChannelPairsForFollowEnrichment indicates an expected call of ListChatterChannelPairsForFollowEnrichment.
func (mr *MockStoreMockRecorder) ListChatterChannelPairsForFollowEnrichment(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatterChannelPairsForFollowEnrichment", reflect.TypeOf((*MockStore)(nil).ListChatterChannelPairsForFollowEnrichment), ctx, limit)
}

// ListDistinctChattersWithMessages mocks base method.
func (m *MockStore) ListDistinctChattersWithMessages(ctx context.Context, limit int) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDistinctChattersWithMessages", ctx, limit)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDistinctChattersWithMessages indicates an expected call of ListDistinctChattersWithMessages.
func (mr *MockStoreMockRecorder) ListDistinctChattersWithMessages(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDistinctChattersWithMessages", reflect.TypeOf((*MockStore)(nil).ListDistinctChattersWithMessages), ctx, limit)
}

// ListEnabledNotificationEntries mocks base method.
func (m *MockStore) ListEnabledNotificationEntries(ctx context.Context) ([]entity.NotificationEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledNotificationEntries", ctx)
	ret0, _ := ret[0].([]entity.NotificationEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledNotificationEntries indicates an expected call of ListEnabledNotificationEntries.
func (mr *MockStoreMockRecorder) ListEnabledNotificationEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledNotificationEntries", reflect.TypeOf((*MockStore)(nil).ListEnabledNotificationEntries), ctx)
}

// ListFollowedMonitoredChannels mocks base method.
func (m *MockStore) ListFollowedMonitoredChannels(ctx context.Context, chatterID int64) ([]entity.FollowedMonitoredChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFollowedMonitoredChannels", ctx, chatterID)
	ret0, _ := ret[0].([]entity.FollowedMonitoredChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFollowedMonitoredChannels indicates an expected call of ListFollowedMonitoredChannels.
func (mr *MockStoreMockRecorder) ListFollowedMonitoredChannels(ctx, chatterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFollowedMonitoredChannels", reflect.TypeOf((*MockStore)(nil).ListFollowedMonitoredChannels), ctx, chatterID)
}

// ListLinkedTwitchAccountUserIDs mocks base method.
func (m *MockStore) ListLinkedTwitchAccountUserIDs(ctx context.Context) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinkedTwitchAccountUserIDs", ctx)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinkedTwitchAccountUserIDs indicates an expected call of ListLinkedTwitchAccountUserIDs.
func (mr *MockStoreMockRecorder) ListLinkedTwitchAccountUserIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinkedTwitchAccountUserIDs", reflect.TypeOf((*MockStore)(nil).ListLinkedTwitchAccountUserIDs), ctx)
}

// ListMonitoredStreams mocks base method.
func (m *MockStore) ListMonitoredStreams(ctx context.Context, f entity.StreamListFilter) ([]entity.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMonitoredStreams", ctx, f)
	ret0, _ := ret[0].([]entity.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMonitoredStreams indicates an expected call of ListMonitoredStreams.
func (mr *MockStoreMockRecorder) ListMonitoredStreams(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMonitoredStreams", reflect.TypeOf((*MockStore)(nil).ListMonitoredStreams), ctx, f)
}

// ListMonitoredTwitchUsers mocks base method.
func (m *MockStore) ListMonitoredTwitchUsers(ctx context.Context) ([]entity.TwitchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMonitoredTwitchUsers", ctx)
	ret0, _ := ret[0].([]entity.TwitchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMonitoredTwitchUsers indicates an expected call of ListMonitoredTwitchUsers.
func (mr *MockStoreMockRecorder) ListMonitoredTwitchUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMonitoredTwitchUsers", reflect.TypeOf((*MockStore)(nil).ListMonitoredTwitchUsers), ctx)
}

// ListNotificationEntries mocks base method.
func (m *MockStore) ListNotificationEntries(ctx context.Context) ([]entity.NotificationEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationEntries", ctx)
	ret0, _ := ret[0].([]entity.NotificationEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationEntries indicates an expected call of ListNotificationEntries.
func (mr *MockStoreMockRecorder) ListNotificationEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationEntries", reflect.TypeOf((*MockStore)(nil).ListNotificationEntries), ctx)
}

// ListRules mocks base method.
func (m *MockStore) ListRules(ctx context.Context) ([]entity.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]entity.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockStoreMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockStore)(nil).ListRules), ctx)
}

// ListTwitchAccounts mocks base method.
func (m *MockStore) ListTwitchAccounts(ctx context.Context) ([]entity.TwitchAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTwitchAccounts", ctx)
	ret0, _ := ret[0].([]entity.TwitchAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTwitchAccounts indicates an expected call of ListTwitchAccounts.
func (mr *MockStoreMockRecorder) ListTwitchAccounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTwitchAccounts", reflect.TypeOf((*MockStore)(nil).ListTwitchAccounts), ctx)
}

// ListTwitchUsers mocks base method.
func (m *MockStore) ListTwitchUsers(ctx context.Context) ([]entity.TwitchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTwitchUsers", ctx)
	ret0, _ := ret[0].([]entity.TwitchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTwitchUsers indicates an expected call of ListTwitchUsers.
func (mr *MockStoreMockRecorder) ListTwitchUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTwitchUsers", reflect.TypeOf((*MockStore)(nil).ListTwitchUsers), ctx)
}

// ListTwitchUsersBrowse mocks base method.
func (m *MockStore) ListTwitchUsersBrowse(ctx context.Context, f entity.TwitchUserBrowseFilter) ([]entity.TwitchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTwitchUsersBrowse", ctx, f)
	ret0, _ := ret[0].([]entity.TwitchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTwitchUsersBrowse indicates an expected call of ListTwitchUsersBrowse.
func (mr *MockStoreMockRecorder) ListTwitchUsersBrowse(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTwitchUsersBrowse", reflect.TypeOf((*MockStore)(nil).ListTwitchUsersBrowse), ctx, f)
}

// ListUserActivityEvents mocks base method.
func (m *MockStore) ListUserActivityEvents(ctx context.Context, f entity.UserActivityListFilter) ([]entity.UserActivityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserActivityEvents", ctx, f)
	ret0, _ := ret[0].([]entity.UserActivityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserActivityEvents indicates an expected call of ListUserActivityEvents.
func (mr *MockStoreMockRecorder) ListUserActivityEvents(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserActivityEvents", reflect.TypeOf((*MockStore)(nil).ListUserActivityEvents), ctx, f)
}

// ListUserActivityEventsForChannelPresence mocks base method.
func (m *MockStore) ListUserActivityEventsForChannelPresence(ctx context.Context, channelTwitchUserID int64, from, to time.Time) ([]entity.UserActivityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserActivityEventsForChannelPresence", ctx, channelTwitchUserID, from, to)
	ret0, _ := ret[0].([]entity.UserActivityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserActivityEventsForChannelPresence indicates an expected call of ListUserActivityEventsForChannelPresence.
func (mr *MockStoreMockRecorder) ListUserActivityEventsForChannelPresence(ctx, channelTwitchUserID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserActivityEventsForChannelPresence", reflect.TypeOf((*MockStore)(nil).ListUserActivityEventsForChannelPresence), ctx, channelTwitchUserID, from, to)
}

// ListUserActivityEventsForTimeline mocks base method.
func (m *MockStore) ListUserActivityEventsForTimeline(ctx context.Context, chatterID int64, from, to time.Time) ([]entity.UserActivityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserActivityEventsForTimeline", ctx, chatterID, from, to)
	ret0, _ := ret[0].([]entity.UserActivityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserActivityEventsForTimeline indicates an expected call of ListUserActivityEventsForTimeline.
func (mr *MockStoreMockRecorder) ListUserActivityEventsForTimeline(ctx, chatterID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserActivityEventsForTimeline", reflect.TypeOf((*MockStore)(nil).ListUserActivityEventsForTimeline), ctx, chatterID, from, to)
}

// ListUserActivityForStream mocks base method.
func (m *MockStore) ListUserActivityForStream(ctx context.Context, f entity.UserActivityListFilterForStream) ([]entity.UserActivityEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserActivityForStream", ctx, f)
	ret0, _ := ret[0].([]entity.UserActivityEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserActivityForStream indicates an expected call of ListUserActivityForStream.
func (mr *MockStoreMockRecorder) ListUserActivityForStream(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserActivityForStream", reflect.TypeOf((*MockStore)(nil).ListUserActivityForStream), ctx, f)
}

// ListUserFollowedChannels mocks base method.
func (m *MockStore) ListUserFollowedChannels(ctx context.Context, followerID int64) ([]entity.FollowedChannelRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserFollowedChannels", ctx, followerID)
	ret0, _ := ret[0].([]entity.FollowedChannelRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserFollowedChannels indicates an expected call of ListUserFollowedChannels.
func (mr *MockStoreMockRecorder) ListUserFollowedChannels(ctx, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserFollowedChannels", reflect.TypeOf((*MockStore)(nil).ListUserFollowedChannels), ctx, followerID)
}

// MonitoredChannelTwitchUserID mocks base method.
func (m *MockStore) MonitoredChannelTwitchUserID(ctx context.Context, channel string) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonitoredChannelTwitchUserID", ctx, channel)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MonitoredChannelTwitchUserID indicates an expected call of MonitoredChannelTwitchUserID.
func (mr *MockStoreMockRecorder) MonitoredChannelTwitchUserID(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonitoredChannelTwitchUserID", reflect.TypeOf((*MockStore)(nil).MonitoredChannelTwitchUserID), ctx, channel)
}

// PatchTwitchAccount mocks base method.
func (m *MockStore) PatchTwitchAccount(ctx context.Context, id int64, accountType *string) (entity.TwitchAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchTwitchAccount", ctx, id, accountType)
	ret0, _ := ret[0].(entity.TwitchAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchTwitchAccount indicates an expected call of PatchTwitchAccount.
func (mr *MockStoreMockRecorder) PatchTwitchAccount(ctx, id, accountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchTwitchAccount", reflect.TypeOf((*MockStore)(nil).PatchTwitchAccount), ctx, id, accountType)
}

// PatchTwitchUser mocks base method.
func (m *MockStore) PatchTwitchUser(ctx context.Context, id int64, patch entity.TwitchUserPatch) (entity.TwitchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchTwitchUser", ctx, id, patch)
	ret0, _ := ret[0].(entity.TwitchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchTwitchUser indicates an expected call of PatchTwitchUser.
func (mr *MockStoreMockRecorder) PatchTwitchUser(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchTwitchUser", reflect.TypeOf((*MockStore)(nil).PatchTwitchUser), ctx, id, patch)
}

// RemoveChannelBlacklist mocks base method.
func (m *MockStore) RemoveChannelBlacklist(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveChannelBlacklist", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveChannelBlacklist indicates an expected call of RemoveChannelBlacklist.
func (mr *MockStoreMockRecorder) RemoveChannelBlacklist(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveChannelBlacklist", reflect.TypeOf((*MockStore)(nil).RemoveChannelBlacklist), ctx, login)
}

// ReplaceChannelChattersSnapshot mocks base method.
func (m *MockStore) ReplaceChannelChattersSnapshot(ctx context.Context, channelTwitchUserID int64, chatterIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceChannelChattersSnapshot", ctx, channelTwitchUserID, chatterIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceChannelChattersSnapshot indicates an expected call of ReplaceChannelChattersSnapshot.
func (mr *MockStoreMockRecorder) ReplaceChannelChattersSnapshot(ctx, channelTwitchUserID, chatterIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceChannelChattersSnapshot", reflect.TypeOf((*MockStore)(nil).ReplaceChannelChattersSnapshot), ctx, channelTwitchUserID, chatterIDs)
}

// ReplaceUserFollowedChannels mocks base method.
func (m *MockStore) ReplaceUserFollowedChannels(ctx context.Context, followerID int64, rows []entity.FollowedChannelRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceUserFollowedChannels", ctx, followerID, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceUserFollowedChannels indicates an expected call of ReplaceUserFollowedChannels.
func (mr *MockStoreMockRecorder) ReplaceUserFollowedChannels(ctx, followerID, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceUserFollowedChannels", reflect.TypeOf((*MockStore)(nil).ReplaceUserFollowedChannels), ctx, followerID, rows)
}

// TruncateChannelChatters mocks base method.
func (m *MockStore) TruncateChannelChatters(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TruncateChannelChatters", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TruncateChannelChatters indicates an expected call of TruncateChannelChatters.
func (mr *MockStoreMockRecorder) TruncateChannelChatters(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateChannelChatters", reflect.TypeOf((*MockStore)(nil).TruncateChannelChatters), ctx)
}

// TwitchUserIDByUsername mocks base method.
func (m *MockStore) TwitchUserIDByUsername(ctx context.Context, username string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TwitchUserIDByUsername", ctx, username)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TwitchUserIDByUsername indicates an expected call of TwitchUserIDByUsername.
func (mr *MockStoreMockRecorder) TwitchUserIDByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TwitchUserIDByUsername", reflect.TypeOf((*MockStore)(nil).TwitchUserIDByUsername), ctx, username)
}

// UpdateIrcMonitorSettings mocks base method.
func (m *MockStore) UpdateIrcMonitorSettings(ctx context.Context, s entity.IrcMonitorSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIrcMonitorSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIrcMonitorSettings indicates an expected call of UpdateIrcMonitorSettings.
func (mr *MockStoreMockRecorder) UpdateIrcMonitorSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIrcMonitorSettings", reflect.TypeOf((*MockStore)(nil).UpdateIrcMonitorSettings), ctx, s)
}

// UpdateNotificationEntry mocks base method.
func (m *MockStore) UpdateNotificationEntry(ctx context.Context, id int64, provider *string, settings map[string]any, enabled *bool) (entity.NotificationEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationEntry", ctx, id, provider, settings, enabled)
	ret0, _ := ret[0].(entity.NotificationEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNotificationEntry indicates an expected call of UpdateNotificationEntry.
func (mr *MockStoreMockRecorder) UpdateNotificationEntry(ctx, id, provider, settings, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationEntry", reflect.TypeOf((*MockStore)(nil).UpdateNotificationEntry), ctx, id, provider, settings, enabled)
}

// UpdateRule mocks base method.
func (m *MockStore) UpdateRule(ctx context.Context, id int64, r entity.Rule) (entity.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, id, r)
	ret0, _ := ret[0].(entity.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockStoreMockRecorder) UpdateRule(ctx, id, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockStore)(nil).UpdateRule), ctx, id, r)
}

// UpdateSuspicionSettings mocks base method.
func (m *MockStore) UpdateSuspicionSettings(ctx context.Context, s entity.SuspicionSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSuspicionSettings", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSuspicionSettings indicates an expected call of UpdateSuspicionSettings.
func (mr *MockStoreMockRecorder) UpdateSuspicionSettings(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSuspicionSettings", reflect.TypeOf((*MockStore)(nil).UpdateSuspicionSettings), ctx, s)
}

// UpdateTwitchRefreshToken mocks base method.
func (m *MockStore) UpdateTwitchRefreshToken(ctx context.Context, id int64, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTwitchRefreshToken", ctx, id, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTwitchRefreshToken indicates an expected call of UpdateTwitchRefreshToken.
func (mr *MockStoreMockRecorder) UpdateTwitchRefreshToken(ctx, id, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTwitchRefreshToken", reflect.TypeOf((*MockStore)(nil).UpdateTwitchRefreshToken), ctx, id, refreshToken)
}

// UpsertChannelChatterPresence mocks base method.
func (m *MockStore) UpsertChannelChatterPresence(ctx context.Context, channelTwitchUserID, chatterTwitchUserID int64) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertChannelChatterPresence", ctx, channelTwitchUserID, chatterTwitchUserID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertChannelChatterPresence indicates an expected call of UpsertChannelChatterPresence.
func (mr *MockStoreMockRecorder) UpsertChannelChatterPresence(ctx, channelTwitchUserID, chatterTwitchUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertChannelChatterPresence", reflect.TypeOf((*MockStore)(nil).UpsertChannelChatterPresence), ctx, channelTwitchUserID, chatterTwitchUserID)
}

// UpsertChannelFollow mocks base method.
func (m *MockStore) UpsertChannelFollow(ctx context.Context, chatterID, channelID int64, followedAt *time.Time, checkedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertChannelFollow", ctx, chatterID, channelID, followedAt, checkedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertChannelFollow indicates an expected call of UpsertChannelFollow.
func (mr *MockStoreMockRecorder) UpsertChannelFollow(ctx, chatterID, channelID, followedAt, checkedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertChannelFollow", reflect.TypeOf((*MockStore)(nil).UpsertChannelFollow), ctx, chatterID, channelID, followedAt, checkedAt)
}

// UpsertHelixMeta mocks base method.
func (m *MockStore) UpsertHelixMeta(ctx context.Context, twitchUserID int64, accountCreatedAt *time.Time, profileImageURL *string, fetchedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertHelixMeta", ctx, twitchUserID, accountCreatedAt, profileImageURL, fetchedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertHelixMeta indicates an expected call of UpsertHelixMeta.
func (mr *MockStoreMockRecorder) UpsertHelixMeta(ctx, twitchUserID, accountCreatedAt, profileImageURL, fetchedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertHelixMeta", reflect.TypeOf((*MockStore)(nil).UpsertHelixMeta), ctx, twitchUserID, accountCreatedAt, profileImageURL, fetchedAt)
}

// UpsertStreamFromHelix mocks base method.
func (m *MockStore) UpsertStreamFromHelix(ctx context.Context, channelTwitchUserID int64, helixStreamID string, startedAt time.Time, title, gameName string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStreamFromHelix", ctx, channelTwitchUserID, helixStreamID, startedAt, title, gameName)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStreamFromHelix indicates an expected call of UpsertStreamFromHelix.
func (mr *MockStoreMockRecorder) UpsertStreamFromHelix(ctx, channelTwitchUserID, helixStreamID, startedAt, title, gameName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStreamFromHelix", reflect.TypeOf((*MockStore)(nil).UpsertStreamFromHelix), ctx, channelTwitchUserID, helixStreamID, startedAt, title, gameName)
}

// UpsertTwitchUserFromChat mocks base method.
func (m *MockStore) UpsertTwitchUserFromChat(ctx context.Context, id int64, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTwitchUserFromChat", ctx, id, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTwitchUserFromChat indicates an expected call of UpsertTwitchUserFromChat.
func (mr *MockStoreMockRecorder) UpsertTwitchUserFromChat(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTwitchUserFromChat", reflect.TypeOf((*MockStore)(nil).UpsertTwitchUserFromChat), ctx, id, username)
}
